export const AUDIO_PROCESSOR_INIT_MESSAGE = 'AUDIO_PROCESSOR_INIT';
export const AUDIO_PROCESSOR_ADD_DATA_MESSAGE = 'AUDIO_PROCESSOR_ADD_DATA';
export const AUDIO_PROCESSOR_RETURN_LATEST_PITCH_DATA_MESSAGE = 'AUDIO_PROCESSOR_RETURN_LATEST_PITCH_DATA';
